### ISSUE TITLE
Supervisor restart starts up services that were explicitly stopped in dashboard

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-supervisor#1120]
User can go to the dashboard, and explicitly stop a service. If then the supervisor restarts for some reason (imaginge: a watchdog, or manual supervisor restart), all the services now restarted and run, even though the user might not have taken any action to do that.

What we expect:

* Services that were stopped explicitly are stopped until app update or explicit restart

Reproduce:

* deploy an application
* stop a service
* connect to host OS and do `systemctl restart resin-supervisor`
* observe that stopped service restarts

**Comment by CameronDiver** [comment]
This is because that any dashboard requests are treated as volatile, and as such the state gets removed after a healthcheck failure. The best method for this would be to find out exactly what was causing the healthcheck failure, and fix that.

We could explore making dashboard requests non-volatile, but we'd need to discuss the implications that this may have.

**Comment by pipex** [comment]
Closed by https://github.com/balena-os/balena-supervisor/pull/1926
