### ISSUE TITLE
depends_on should trigger service re-creation when the service it depends on has changed

### ISSUE THREAD

**Issue by pdcastro** [balena-os/balena-supervisor#1151]
If a service dependency is declared with the `depends_on` instruction in the `docker-compose.yml` file, so that service A depends on service B, then service A should be restarted if service B is restarted. For example, a change to an environment variable of service B should cause both B and A to be restarted (probably stop A; restart B; (re)start A).

Originally raised as a `balena-cli` issue. Check for full details:
https://github.com/balena-io/balena-cli/issues/1447

**Comment by maggie0002** [comment]
Why? Not sure I get why someone would want this to happen. Changes to an env file or var in service B has no relation to service A, service A has it's own env files and vars. Triggering a recreate on service A if I change service B just means I have to recreate the same image again, with no gain and the cost of the time and resources to rebuild it. 

https://github.com/balena-io/balena-cli/issues/1447
https://github.com/balena-io-modules/livepush/issues/58

**Comment by 20k-ultra** [comment]
Paulo had re-used the title from https://github.com/balena-io/balena-cli/issues/1447 but their description is saying the Service A should be restarted if Service B is modified. The use of re-create might imply re-create the image or container but I cam confident that is not what is intended here.

I think what we can debate is weather or not Service A should be restarted when Service B is modified and restarted. Depends_on is a compose mechanism to control the order of startup as you mentioned and therefore has no impact on operation once running. Therefore I think the most appropriate behavior is to not restart Service A if Service B is since that behavior does not exist for docker users.

Thoughts?

**Comment by 20k-ultra** [comment]
I understand there may be some improvements for the user's application if they don't have to worry about re-checking another services state. For example if Service A was an HTTP API service which depended_on Service B which is a Redis instance then on restart of Service B due to a config change Service A may not recover from the disconnect. However, this is an issue the user's application should handle and we shouldn't add this new behavior that can catch people off guard.

**Comment by maggie0002** [comment]
Sounds about right to be. I can think of many more instances where restarting a container because another one has been asked to restart could cause issues that we then can't prevent. Whereas if I need two containers to restart, I can come up with ways to do so.

**Comment by 20k-ultra** [comment]
Slight clarification is that this issue is only for container changes not release. A release change would trigger a new release build which pulls the new service images and re-creates. However, this issue is describing a container change which triggers a restart which to my knowledge is limited to service variable changes.

**Comment by 20k-ultra** [comment]
I just performed a test to see if docker-compose will restart both services when I modify the depended on service and it did not.

**Comment by 20k-ultra** [comment]
Since the current behavior matches docker-compose I will close this issue.
