### ISSUE TITLE
supervisor should not start after a HUP without checking the breadcrumbs (this ensure the hup rollback services have run and all is ok))

### ISSUE THREAD

**Issue by floion** [balena-os/balena-supervisor#1459]
After a HUP the device is rebooted. When the boards boots, there are a few systemd rollback services that run to ensure the HUP was ok. These services are `rollback-health` and `rollback-altboot`. The supervisor should only start after these rollback services have finished. If the supervisor starts while these services have not finished then the supervisor may reboot the board (for example if the target state is different from the current state, the supervisor will do the changes to apply the target state and reboot the board) and if the rollback services have not done their part (clear upgrade_available, reset boot counter etc) then at next boot the board will boot from wrong rootfs as well as other bad things will happen (especially on nvidia based boards)

**Comment by 20k-ultra** [comment]
hey @xginn8, there's been a lot of work done on HUP so just checking this is something the Supervisor will still need to implement.

**Comment by xginn8** [comment]
@20k-ultra as the supervisor absorbs some of the functionality of HUP as part of tri-app, we'll need to figure this out in the supervisor itself.

**Comment by 20k-ultra** [comment]
Is this something the Supervisor should start implementing or do we need to figure out / implement some other bits ?

**Comment by acostach** [comment]
@20k-ultra @xginn8 do you have any updates on this?

**Comment by xginn8** [comment]
i think this can be implemented in the supervisor. basically, until rollbacks have completed, no changes should be applied.

**Comment by 20k-ultra** [comment]
Is the Supervisor just checking the status of rollback-health and rollback-altboot to be exited ? That seems pretty trivial and we just have to discuss what should the Supervisor do if there are breadcrumbs. 

I like the idea of the Supervisor doing this check tbh. It seems like it will prevent a severe class of issues and absorbs HUP responsibilities since we'd like all applications (Supervisor is one) to be managed the same. What they do when running is up to them.

**Comment by 20k-ultra** [comment]
we can created a "reboot lock" much like an update lock. When the reboot lock exists the Supervisor will never try to reboot the device.

The first implementation of reboot locks doesn't have to look for a reboot.lock file, instead we can just check if the "breadcrumbs" which the rollback services themselves check to see if they should rollback. If these state files exist (unsure what they are exactly at this time) then convey that there is a reboot lock.

**Comment by cywang117** [comment]
Closing this issue: This is resolved with PR #1723 and will be available with Supervisor v12.8.10. The deployment for this Supervisor version will be made available via [self-serve upgrades](https://www.balena.io/docs/reference/supervisor/supervisor-upgrades/). Because Jetson devices are sensitive to bricking upon HUP if the Supervisor reboots the device during, balenaOS 2.73.1+rev4 for Jetson device types will be updated in the balena-os/meta-balena repo to set its Supervisor version to v12.8.10 as well. (There may be other balena OS versions and/or device types that will have their Supervisor versions updated, I'll edit this comment with them if that's the case.)

I commented in #1723 that there's is a possible case with the rollback-altboot service where breadcrumbs are not created, and thus I wanted to keep this issue open. However, after investigating, I believe this is a non-factor and this issue may be closed. I'll explain my rationale below for future reference:

#### Context: 
HUP (Host OS update) is balena's mechanism for in-place balenaOS upgrades on the device, which may be triggered remotely, most commonly via dashboard. During HUP, here is a rough idea of the device's actions:
1. User triggers HUP. As long as HUP is not triggered via CLI, the Supervisor (SV) version that comes with the target OS version will also be downloaded. (I'll move forward with the assumption that SV is also updated.)
2. Device downloads target host OS image into the [inactive root partition](https://www.balena.io/os/docs/architecture/#Image-Partition-Layout), then triggers reboot.
3. Device reboots into previously inactive root partition where target OS was just downloaded. HUP hooks will run, which includes healthchecks which, on failure, trigger rollback. At the start of these update hooks, *two* breadcrumb files will be created in the state partition (`/mnt/state` on the host OS). 
4. If healthchecks succeed, breadcrumb files are deleted.
5. If healthchecks fail, rollback is triggered and the device reboots into the previous partition which contains the old OS.

The 2 rollback services are as follows:
- rollback-health: makes sure openVPN service and balena service (engine) are healthy in the new OS)
- rollback-altboot: checks existence of init file in new OS.

#### Explanation:
I mentioned in the PR that there's a case where rollback-altboot doesn't create breadcrumbs. This is not an issue, because:
- resin-supervisor.service cannot start until balena.service starts. [Reference](https://github.com/balena-os/meta-balena-distro/blob/fb6faefda1f9b920f48e8f36c4246a93ac09ab71/meta-balena-common/recipes-containers/resin-supervisor/resin-supervisor/resin-supervisor.service#L8-L16).
- balena.service cannot start until rollback-altboot.service finishes. [Reference](https://github.com/balena-os/meta-balena-distro/blob/fb6faefda1f9b920f48e8f36c4246a93ac09ab71/meta-balena-common/recipes-containers/balena/balena/balena.service#L6)
- If rollback-altboot.service [reboots](https://github.com/balena-os/meta-balena-distro/blob/fb6faefda1f9b920f48e8f36c4246a93ac09ab71/meta-balena-common/recipes-core/balena-rollback/files/rollback-altboot#L33) because of broken boot init in the new OS, rollback-altboot will never complete and balena.service & resin-supervisor.service will never launch. Thus a rollback-altboot condition and a Supervisor rebooting during HUP condition can never coexist.

In the case of rollback-health, breadcrumbs are always created, and we ensure update locks while breadcrumbs exist in #1723. Thus, the cases covered by this issue are completely covered by that PR.

#### Q&A
1. Why/when does Supervisor reboot my device while HUP has not finished?
    - When there's a change made to the device target state on the cloud that requires a reboot, such as updating a boot config via the dashboard (See [here](https://github.com/balena-os/balena-supervisor/blob/master/docs/configurations.md)), Supervisor will receive this as target state soon after it starts, and will trigger a reboot. This can also occur during HUP which is undesirable. Before this PR, the Supervisor was not HUP-aware, so there wasn't such a thing as a conditional reboot, unless users had set an [update lock](https://www.balena.io/docs/learn/deploy/release-strategy/update-locking/) on their device which prevented containers from being killed by the Supervisor.
2. How can I make sure HUP doesn't brick my device if my target OS version doesn't come with Supervisor v12.8.10?
    - This issue is relatively rare. It only occurs when you set a boot config during a HUP, and even then, only if healthchecks in the new OS fail. Additionally, certain device types are more susceptible to this issue than others, namely Jetson devices. 
    - As a workaround, you can delay setting configs until after HUP has completed. You may do this programmatically as well, by writing your script to periodically check `/mnt/state` to make sure `rollback-altboot-breadcrumb` and `rollback-health-breadcrumb` are gone before patching your configs.
    - As another workaround, upgrade Supervisor version via self-serve to 12.8.10 prior to HUP. If your device's Supervisor version is newer than the version that comes with the target OS version, the device will keep the newer version. [Reference](https://forums.balena.io/t/what-happens-during-a-resin-host-os-update/2087)

Note that this comment only applies to Upgrading between balenaOS 2.x versions. If you're running balenaOS 1.x, please upgrade ASAP.
