### ISSUE TITLE
Hard to recover device stuck in Updating state

### ISSUE THREAD

**Issue by majorz** [balena-os/balena-supervisor#1633]
Device type: Raspberry Pi 3
OS version: balenaOS 2.72.0+rev1
Supervisor version: 12.3.5

A single container device was stuck in Updating state at 98%. The customer said that the container image was downloaded and running, but the progress has not updated. I saw a traceback coming from the application which possibly was related to this. There were different indications for unstable network (DNS resolution tracebacks, I needed a few tries until I login successfully, device went at one point into "Online (VPN only)" mode).

I restarted supervisor - nothing changed. Rebooted the device - nothing changed again. Deleted the supervisor database - same result. Deleted all containers (including supervisor) and run update-resin-supervisor - the supervisor image got redownloaded, but the container was still stuck in Updating state. Finally I did a new reboot after the cleanup and the container image download was started from scratch.

Device diagnostics are attached in the corresponding JF item below.

**Comment by 20k-ultra** [comment]
Since the device went into "Online (VPN only)" mode and logs contain the following message we know that the update state couldn't change due to network connectivity issues.
```
Mar 30 15:53:56 12957a4 resin-supervisor[7923]: [error]   LogBackend: unexpected error: Error: getaddrinfo EAI_AGAIN api.balena-cloud.com
Mar 30 15:53:56 12957a4 resin-supervisor[7923]: [error]         at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
```
Someone confirmed the network was having issues because of:

```
/usr/src/app # curl -v -I api.balena-cloud.com
* Could not resolve host: api.balena-cloud.com
* Closing connection 0
curl: (6) Could not resolve host: api.balena-cloud.com
```

It was also found that the application on that device was modifying the network interfaces on the device causing the connectivity issue preventing the Supervisor from reaching our API.
