### ISSUE TITLE
API docs: Clarify behavior of POST /v1/restart

### ISSUE THREAD

**Issue by pdcastro** [balena-os/balena-supervisor#1681]
Some users get surprised that the restart operation causes containers to be re-created, and that restart is not the same as stop + start. Document this. See also #1116 and balena-io/balena-ui/issues/3099.

https://www.balena.io/docs/reference/supervisor/supervisor-api/#post-v1restart

**Comment by 20k-ultra** [comment]
@cywang117 do you know where we plan explain the behaviour you documented in https://github.com/balena-os/balena-supervisor/issues/1116#issuecomment-832079939

**Comment by cywang117** [comment]
@20k-ultra Definitely the above endpoints, and also `/v2/applications/:appId/restart`, since it calls the same method under the hood as `/v1/restart` and we haven't specified that this endpoint removes containers. Basically, we should explain that containers are removed wherever there's a restart endpoint in the docs.
