### ISSUE TITLE
Supervisor not restarting proxy in balenaOS >= v2.82.0

### ISSUE THREAD

**Issue by pipex** [balena-os/balena-supervisor#1775]
In balenaOS [v2.82.0](https://github.com/balena-os/meta-balena/blob/master/CHANGELOG.md#v2820) the `resin-proxy-config` service was renamed to `balena-proxy-config` but the supervisor was not updated  accordingly here

https://github.com/balena-os/balena-supervisor/blob/master/src/host-config.ts#L155-L156

Same thing for `resin-hostname` here https://github.com/balena-os/balena-supervisor/blob/master/src/host-config.ts#L167

Fix should be easy but we'll need to try both versions until we have a specific OS cutoff

**Comment by klutchell** [comment]
I'll fix this up since we have releases in production with this name change.

Going forward, the OS will actually restart the related services automatically when certain files change.

1. https://github.com/balena-os/meta-balena/pull/2294
2. `resin-proxy-config` and `redsocks` TODO

In that case we actually want to ensure the supervisor does not try to restart these services. Not sure of the best way to approach that offhand without checking the OS version. Maybe there's some other state we could check before attempting to restart these services via the supervisor.

**Comment by pipex** [comment]
@klutchell I think you already found the solution in #1776?

**Comment by klutchell** [comment]
> @klutchell I think you already found the solution in #1776?

Yeah, checking if they are part of certain target units will determine if they need to be restarted or not. I haven't tested that PR yet so it's still in Draft ATM.
