### ISSUE TITLE
Error: (HTTP code 404) no such network - network supervisor0 not found

### ISSUE THREAD

**Issue by pdcastro** [balena-os/balena-supervisor#1806]
Supervisor version 12.10.15:

```
[error]   Scheduling another update attempt in 900000ms due to failure:  Error: (HTTP code 404) no such network - network supervisor0 not found 
[error]         at /usr/src/app/dist/app.js:10:2333800
[error]       at /usr/src/app/dist/app.js:10:2333732
[error]       at Modem.buildPayload (/usr/src/app/dist/app.js:10:2333752)
[error]       at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:10:2333005)
[error]       at IncomingMessage.emit (events.js:322:22)
[error]       at endReadableNT (_stream_readable.js:1187:12)
[error]       at processTicksAndRejections (internal/process/task_queues.js:84:21)
[error]   Device state apply error Error: (HTTP code 404) no such network - network supervisor0 not found 
[error]         at /usr/src/app/dist/app.js:10:2333800
[error]       at /usr/src/app/dist/app.js:10:2333732
[error]       at Modem.buildPayload (/usr/src/app/dist/app.js:10:2333752)
[error]       at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:10:2333005)
[error]       at IncomingMessage.emit (events.js:322:22)
[error]       at endReadableNT (_stream_readable.js:1187:12)
[error]       at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

The state was:

* `ifconfig` showed that a `supervisor0` interface existed
* `balena-engine network ls` showed that a `supervisor0` network did **not** exist
* Restarting the supervisor would not fix it.

The following manual intervention "fixed it":

```sh
$ systemctl stop resin-supervisor
$ ip link del supervisor0
$ systemctl start resin-supervisor
```

The `ip link del` command deletes the interface as listed by `ifconfig`.

Tentative conclusion: The `supervisor0` entity exists both as a system interface, as listed by `ifconfig`, and as a balenaEngine network, as listed by `balena-engine network ls`. The existence of the former prevents the supervisor from creating the latter. The solution would thus be for the supervisor to independently inspect and create both `supervisor0` entities.

**Comment by alexszilagyi** [comment]
@pdcastro , @pipex : Any updates on this?

**Comment by toochevere** [comment]
This was observed after an issue where there was apparent docker folder corruption that required wiping the docker data.  It would suggest that this issue might appear when there is an inconsistency in the docker state.  I suspect that the network was left over from the previous state, and was therefore not recreated when the supervisor was restarted, which left it in a weird place where it could not create the network and at the same time it could not see the existing network.

**Comment by pipex** [comment]
I have not been able to get the device to the right conditions to try to replicate this issue. Doing `balena network rm supervisor0` correctly removes the docker network as well as the interface, which means some corruption is happening somewhere in order to produce this state.

Even with that I would expect the supervisor to recover from this condition eventually. The reason it doesn't is probably because the supervisor assumes the network interface got erased with the docker network. A more robust mechanism would be to try to remove the interface if it still exists.

https://github.com/balena-os/balena-supervisor/blob/2615c25fc48d4e40cf6ec8ecf567621bd261e9f0/src/compose/network-manager.ts#L91-L97

Once we move to the supervisor being a full app, we might be able to get rid of the `supervisor0` name, since having a static name is probably causing additional issues (including #1110). In that future, the supervisor network will just exist on the supervisor container and adding the API label will add the user app to the supervisor network, no matter the network name.

**Comment by pipex** [comment]
I managed to replicate this, it looks it is indeed related to corruption. Here are the replication steps

- Provision a device with an app using the `io.balena.features.supervisor-api` label
- Wait for the device to create the `supervisor0` network
- Stop the supervisor and engine `systemctl stop balena-supervisor && systemctl stop balena-engine`
- Remove the docker network store `rm /var/lib/docker/network/files/local-kv.db`
- Start the engine and supervisor `systemctl stop balena-supervisor && systemctl stop balena-engine`
- The supervisor logs will now show `Error: (HTTP code 404) no such network - network supervisor0 not found`
