### ISSUE TITLE
Supervisor does not start preloaded app when device is offline (> 12.11.16)

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#1895]
The bug is that, when the device does not have internet connection on startup, the Supervisor will not start preloaded apps until it has been restarted. After Supervisor is restarted once, it will start up the preloaded app immediately. 

However, the Supervisor WILL rename `apps.json` -> `apps.json.preloaded` and will add the correct data to the `app` table of the database.

**Comment by 20k-ultra** [comment]
The problem is that the Supervisor sets and applies the target state in 2 steps. On start the Supervisor will run a function called `loadInitialState` which performed these 2 steps but it was not applying the loaded state. This is because the condition to apply the state checks if a state has been set but that variable was referencing an outdated value. This is why after restart the Supervisor would run the preloaded applications because the first run the preloaded apps are set in the target state but not ran because there was no state previously set. Now with the state set, on restart, the config telling the Supervisor a state is set it will apply it.

The solution was to check if a target state has been set or if the recent execution of setting the target state did set the state.

**Comment by cywang117** [comment]
Fixed in Supervisor version 12.11.38.
