### ISSUE TITLE
Supervisor process cleanup could be more efficient

### ISSUE THREAD

**Issue by cywang117** [balena-os/balena-supervisor#2100]
Currently, the Supervisor performs some shutdown operations on receiving a SIGKILL, but I don't believe it receives a SIGTERM for some reason, not necessarily because of the use of `/bin/sh`. This results in shutdown commands sent by the Engine taking 10s each time. 

We can either shorten this grace period by setting `stop_grace_period` in the production Supervisor's docker-compose.yml (this requires Supervisor-as-an-app), or capturing SIGTERM somehow and explicitly calling `process.exit(0)` after all cleanup operations have been completed.

**Comment by cywang117** [comment]
Per @hraftery , for processes like `sleep` and the Supervisor that do not have an explicit handler for SIGTERM, the kernel steps in and kills them except if they're PID 1: https://raby.sh/sigterm-and-pid-1-why-does-a-container-linger-after-receiving-a-sigterm.html

**Comment by Bucknalla** [comment]
Just as a note, please be sure to update the customer on this [ticket](https://jel.ly.fish/support-thread-1-0-0-front-cnv-dntur9p) when we have a resolution :)

**Comment by pipex** [comment]
Extra information. The supervisor runs with pid 1, and node [should receive SIGTERM](https://stackoverflow.com/questions/65677272/what-is-the-default-behaviour-of-node-js-on-receiving-sigterm). As far as I can tell we are not catching SIGTERM in the code so further experimentation needs to happen to see why SIGTERM is not being received

**Comment by hraftery** [comment]
Extra, extra information. Other services that are instantiated in the same way as the supervisor (ie. as a [shell script in a `CMD` statement in *exec* form](https://github.com/balena-os/balena-supervisor/blob/c833d016ff8143aaf77774682efbaa96a365287b/Dockerfile.template#L206)) receive `SIGTERM` just fine. MRE:

- `Dockerfile.template`

```
FROM balenalib/%%BALENA_ARCH%%-alpine
COPY go.sh /
CMD ["/go.sh"]
```

- `go.sh`

```
#!/bin/sh

trap 'echo got_term' 15; while true; do sleep 1; done
```

Pushing this application to a balena device results in a service `main`, which logs "got_term" when it receives `SIGTERM`. This happens both when opening a shell in the service and running `kill -SIGTERM 1`, or when issuing `balena stop <container id>` from HostOS.

In this way the behaviour is exactly as it is in Docker, so rules out any obvious complications introduced by balenaOS.

Note however, that the Docker documentation on the difference between the *exec* and *shell* form of the `RUN` and `ENTRYPOINT` is highly misleading and confusion abounds. It says "the *shell* form ... will be started as a subcommand of  `/bin/sh -c`, which does not pass signals". This depends on the shell and is [not true in general](https://stackoverflow.com/questions/52968361/different-process-are-running-as-pid-1-when-running-cmd-entrypoint-in-shell-form). In this case we're using Alpine and I could detect no difference in the way signals arrive in the container between the *exec* and *shell* forms.

End of extra information and on to speculation:

The Supervisor's [entry script](https://github.com/balena-os/balena-supervisor/blob/c833d016ff8143aaf77774682efbaa96a365287b/entry.sh#L77) `exec`s the node interpreter. So it's not obvious to me why the script would be involved once the supervisor is running. Further, the supervisor [doesn't appear to](https://github.com/balena-os/balena-supervisor/search?q=SIGTERM) have a `SIGTERM` handler. However, [apparently](https://stackoverflow.com/a/65679246/3697870) node's default behaviour for scripts that don't have a handler is to "exit the process immediately". So something doesn't add up.

**Comment by pipex** [comment]
Found the following info that seems pretty official (coming from nodejs) 

> Node.js was not designed to run as PID 1 which leads to unexpected behaviour when running inside of Docker. For example, a Node.js process running as PID 1 will not respond to `SIGINT` (`CTRL-C`) and similar signals. As of Docker 1.13, you can use the `--init` flag to wrap your Node.js process with a [lightweight init system](https://github.com/krallin/tini) that properly handles running as PID 1.

[reference](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals)

In my tests I could confirm this by opening a shell into the container and running `signal -15 1`. If running node, the signal is ignored, but running with `tini`, the container exists immediately.

If running `node` as PID 1. I found that adding a `SIGTERM` handler on the code was enough to make the process respond to the signal. 

However it seems like the [best practice in this case is to use tini](https://blog.ghaiklor.com/2018/02/20/avoid-running-nodejs-as-pid-1-under-docker-images/#tini). So I'll create a PR using that after I run some local tests

**Comment by hraftery** [comment]
Seems official but I'm concerned it's just glossing over a misunderstanding.

I know we've recommended `tini` to customers before for their services - there was a ticket where a user had hundreds of zombie processes that were clogging things up and they were using some third party app (`telegraf` maybe?) as their entry point. I can't remember the details and unfortunately Jellyfish just keeps giving me results with "tiny" in them instead, like [Tiny Fart Bubbles from Sugar Land](https://jel.ly.fish/contact-g-tiny-fart-bubbles).

Anyway, this point is that an init system is a big, blunt bandaid when we could fix the root cause instead.

I too had no trouble adding a responsive handler when `node` is PID 1. Normally I'd suggest that the fact that the node community seems wilfully ignorant of this Linux behaviour, that we need to follow suit. But in this case we control both the Linux distro and the node version, so for me that's enough justification to doing it right. If the handler fails, then Docker comes along and kills the process and we're no worse off.

Here's my MRE (for Docker instead of balena-engine just for convenience) of this working:

- `Dockerfile`

```
FROM node:16-alpine3.16

COPY entry.sh /
COPY app.mjs /

CMD ["/entry.sh"]
```

- `entry.sh`

```
#!/bin/sh

exec node /app.mjs
```

- `app.mjs`

```
import process from 'node:process';
import child from 'node:child_process';


//Step 1: register signal handlers - SIGINT just logs, SIGTERM exits.

process.on('SIGINT', () => {
  console.log('Received SIGINT. Ignoring.');
});

process.on('SIGTERM', () => {
  console.log('Received SIGTERM. Exiting.');
  process.exit(1);
});


//Step 2: log that we're up and running.

console.log("Started.");


//Step 3: spawn a long running child process that doesn't have its own signal handling.

child.exec('sleep infinity', (error, stdout, stderr) => {
  if (error)  { console.log(`Child error: ${error.message}`); }
  if (stderr) { console.log(`Child stderr: ${stderr}`); }
  if (stdout) { console.log(`Child stdout: ${stdout}`); }
});


//Step 4: sit and wait, just logging periodically

while (true) {
  await new Promise(resolve => setTimeout(resolve, 5000));
  console.log("Still alive...");
}
```

After running `docker build .` and `docker run`, I see the process tree I expect, including a child of the node process:

```
/ # ps -o pid,ppid,user,time,args
PID   PPID  USER     TIME  COMMAND
    1     0 root      0:00 node /app.mjs
   18     1 root      0:00 sleep infinity
   19     0 root      0:00 /bin/sh
   25    19 root      0:00 ps -o pid,ppid,user,time,args
```

And the log shows the results I expect when either sending a signal directly or using docker to stop the container:

```
2023-01-30 14:10:19 Started.
2023-01-30 14:10:25 Still alive...
...
2023-01-30 14:11:40 Still alive...
2023-01-30 14:11:40 Received SIGINT. Ignoring.
2023-01-30 14:11:45 Still alive...
2023-01-30 14:11:47 Received SIGTERM. Exiting.
```

No delays and no left over processes.

So adding a `SIGTERM` handler to Supervisor, even it if's just to run `exit(1)` at first, seems like the right thing to do now, eliminates a host of potential issues/confusion/dependency in the future, and paves the way for a cleaner shutdown if that turns out to be useful (even just logging the even might prove useful).

**Comment by pipex** [comment]
> But in this case we control both the Linux distro and the node version, so for me that's enough justification to doing it right. If the handler fails, then Docker comes along and kills the process and we're no worse off.

This was my main worry, that having the handler trigger when the Node process is PID 1 might be more of a fluke than what's officially expected. But you are right that the worst case scenario is that we are left in the same state and we are potentially introducing new failure modes by adding an additional process.

**Comment by hraftery** [comment]
Yeah, fair concern. I satisfied myself because:

1. After reading those Node best practices and comparing with other sources, it seems Node doesn't even *know* it is running as PID 1, so the `tini` recommendation is likely a reaction to the confusion around Linux's different treatment of `SIGTERM` for PID 1, rather than any technical limitation or deliberate design decision.
2. We can produce and control for a stable scenario that behaves as expected, and test for regressions.
3. That giving something as critical as supervisor a configurable number of seconds to see itself out or get the boot, is a reasonable thing to do, is well-known behaviour in Linux/containerisation land, and is likely to provide the minimum amount of surprise in many stop/start/fault scenarios.
